### ISSUE TITLE
Higher precision

### ISSUE THREAD

**Issue by jottoy** [tompollard/tableone#118]
Hello,

thank you for this nice toolbox!
Is there a way to increase the precision of the numbers in the output table?

Thank you!

**Comment by vldud-off** [comment]
@jottoy check the parameter *decimals* in TableOne class

**Comment by tompollard** [comment]
That's right @jottoy, you should be able to set the precision using `decimals`. e.g. 

```
# set decimal places for height to 3
decimals = {"weight": 3}
```
