### ISSUE TITLE
TableOne Docstrings not visible in Docs?

### ISSUE THREAD

**Issue by eroell** [tompollard/tableone#159]
Hi all,

thanks a lot for this cool package!

I have been wondering on the docs page https://tableone.readthedocs.io/en/latest/tableone.html, whether there shouldn't be the docstrings of `TableOne` and its methods visible?
To me, independent of browser, they do not appear.

My apologies if I am confusing something here?

**Comment by tompollard** [comment]
Thanks for picking this up Elias. Now fixed: https://tableone.readthedocs.io/en/latest/tableone.html

![Screenshot 2024-06-15 at 12 22 48 AM](https://github.com/tompollard/tableone/assets/822601/554cfd05-efa3-48c6-9568-c8a2b698271d)
