### ISSUE TITLE
Installation issue: Numpy deprecating builtin types (np.long)

### ISSUE THREAD

**Issue by inescgu** [tompollard/tableone#168]
See numpy deprecation notice: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

np.long is used in the package and could be replaced with either np.longlong or np.int_ depending on use case.

**Comment by tompollard** [comment]
Thanks for flagging this @inescgu. I have taken a look over the repo and I don't see any obvious uses of the deprecated syntax. 

e.g. a search for `np.long` just returns this issue: https://github.com/search?q=repo%3Atompollard%2Ftableone%20np.long&type=code

Is it possible that the deprecation warning came from somewhere else, e.g. a dependency or in code that was making use of tableone?

**Comment by inescgu** [comment]
yes absolutely @tompollard  the error came from having an old version of statsmodels installed. thanks for flagging - apologies for the confusion. will close this issue.

**Comment by tompollard** [comment]
thanks @inescgu and no problem, i appreciate you raising this anyway!
