### ISSUE TITLE
standardise documentation

### ISSUE THREAD

**Issue by tompollard** [tompollard/tableone#21]
ref: https://github.com/tompollard/tableone/issues/19

> ...reasonably documented, but does not follow a standard documentation convention or style.

**Comment by alistairewj** [comment]
I went back and forth on formats - finally settled on using  https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#docstring-standard which I think we had sort of started with. We're also now using sphinx to build the docs and hosting on readthedocs using the readthedocs theme. The docs are also auto importing the doc strings which is quite a nice feature! I think we can close this?

**Comment by tompollard** [comment]
Thanks for doing this. Just as a reminder, the docs are at:
http://tableone.readthedocs.io/en/latest/

I'd like to add a little more detail to the docs (arguments, the table object, etc), but we can close this for now and open a new issue later when needed.
