### ISSUE TITLE
appropriateness of summary descriptive statistics with respect to modality

### ISSUE THREAD

**Issue by tompollard** [tompollard/tableone#22]
ref: https://github.com/tompollard/tableone/issues/19

> While categorical variables are being considered, all other variables are being described in terms of a unimodal perspective. This can be potentially dangerous, since mean, medians, standard deviations, and IQRs are only appropriate for the interpretation of unimodal distributions. This is a basic problem in the biomedical field as a whole; however, these types of tools like tableone may actually facilitate the inappropriate use of summary descriptive statistics in the misinterpretation of study data.

> ...the authors should address issues of the appropriateness of summary descriptive statistics with respect to modality 

> ...... Possible approaches include providing facilities to (self)identify non-unimodal distributions ... Try to go the next step and prevent possible misinterpretation of data.

**Comment by jraffa** [comment]
So I would suggest two things:

1: Hartigan's Dip Test: 
https://cran.r-project.org/web/packages/diptest/

2: Some clever way to link a plot (histogram or kernel density estimate) in the output.

**Comment by tompollard** [comment]
Thanks Jesse. I'm not sure there is an existing implementation of the diptest in Python, so we might need to code this ourselves, unless we can find a good alternative.

We can look into incorporating plots, though I would prefer to avoid this if possible, mainly because it would need several additional dependencies and expands the scope somewhat.

**Comment by jraffa** [comment]
Have not vetted, but:
https://github.com/alimuldal/diptest

**Comment by tompollard** [comment]
It's not available on PyPi and I'd prefer to avoid the GPL license, so not sure it's going to be useful unfortunately.

**Comment by tompollard** [comment]
https://projecteuclid.org/DPubS?service=UI&version=1.0&verb=Display&handle=euclid.aos/1176346577

**Comment by tompollard** [comment]
Pull request: https://github.com/tompollard/tableone/pull/44 adds hartigan's Dip Test to the `cont_describe` table:

![screen shot 2018-03-20 at 09 33 11](https://user-images.githubusercontent.com/822601/37659385-3538ad6c-2c26-11e8-8f05-b5ac8659bee1.png)

Also raises warnings if possible multimodality is detected:

![screen shot 2018-03-20 at 09 33 58](https://user-images.githubusercontent.com/822601/37659388-38799ee6-2c26-11e8-90b0-4b0228b88b9a.png)
