### ISSUE TITLE
make installable from conda forge

### ISSUE THREAD

**Issue by alistairewj** [tompollard/tableone#27]
https://conda-forge.github.io

**Comment by tompollard** [comment]
https://conda-forge.org/docs/recipe.html

**Comment by tompollard** [comment]
Recipe submitted: https://github.com/conda-forge/staged-recipes/pull/5265

**Comment by tompollard** [comment]
Recipe merged :) Need to check that conda installation works correctly before closing this issue.

**Comment by tompollard** [comment]
Feedstock details are at: https://github.com/conda-forge/tableone-feedstock

**Comment by fw2274** [comment]
Closed #27
