### ISSUE TITLE
Add a `remarks` column highlighting issues to consider

### ISSUE THREAD

**Issue by tompollard** [tompollard/tableone#28]
Add a `remarks = True` argument, that adds a remarks column to the table (alternatively notes/ comments/ summary/ observations/ concerns). The column can be used to highlight concerns discussed in #20 (+ #22 and #23). 

e.g. append comments along the lines of: 
- "Heavy outliers: Is it appropriate to report the mean?"
- "Distribution appears to be bimodal:Is it appropriate to report the mean?".
- "Distribution is skewed..."
- etc.

**Comment by alistairewj** [comment]
Wouldn't warnings make more sense?

**Comment by tompollard** [comment]
I'd thought about this, but a remarks column seems friendlier for this kind of thing? A page full of warnings to say that distributions are skewed would be pretty abrasive and might conceal more important issues or cause people to switch off warnings altogether.

My preference is to use warnings for major issues, and then remarks for points to consider. Ideally the remarks would be included in the notebook, and only suppressed when writing to the document format.

**Comment by tompollard** [comment]
Statsmodels highlights potential issues with a "warning" message below the model output (without actually raising a warning). e.g. see: http://www.statsmodels.org/dev/example_formulas.html

![screen shot 2018-03-10 at 23 09 41](https://user-images.githubusercontent.com/822601/37249573-2788af7a-24b8-11e8-9f09-74b245ad58f2.png)
