### ISSUE TITLE
variables all sorted alphabetically in output

### ISSUE THREAD

**Issue by col-slade** [tompollard/tableone#29]
Hi thanks a lot for making this !

The example output in the readme.md file is sorted by the order of the columns.

When I call TableOne, the output is listed alphabetically, I would like to print them in the order that I entered - is there a way to achieve that?

I am using version 0.4.9 with python 3.6.2

Thanks again

**Comment by tompollard** [comment]
Thanks @col-slade, glad it's helpful! At the moment you are limited to the alphabetical sorting unfortunately. The example is from a previous version, which had a slightly different sorting method.  I'll fix this issue soon, hopefully in the next week or two. If you can think of additional functionality you would like to see, please raise issues!

**Comment by col-slade** [comment]
Thanks for the quick response, would be great to be able to determine the order and No. 1 request

**Comment by tompollard** [comment]
@col-slade the issue should be resolved in v0.5.0 (pip installable) with the new `sort` argument.

```
    sort: Boolean
        Sort the rows alphabetically. Default (False) retains the input order 
        of columns.
```

If it looks good on your side, this issue can be closed.

**Comment by tompollard** [comment]
@col-slade I think this issue has been resolved in the update, but please re-open it if not.

**Comment by col-slade** [comment]
Works like a charm, thanks !
