### ISSUE TITLE
Raise warning for outliers

### ISSUE THREAD

**Issue by tompollard** [tompollard/tableone#35]
Related to #19, #22 and #28. Might also be worth raising a warning if outliers appear to be heavily influencing the summary statistics. What is a good approach? (e.g. simple check might be to compare trimmed mean with mean?).

**Comment by jraffa** [comment]
Tukey's rule is pretty common, although the interpretation depends on the circumstances.  

I may just apply this rule, and suggest the user plot the data to check.

**Comment by tompollard** [comment]
Thanks Jesse. Tukey's rule will be straightforward to incorporate, assuming you mean this IQR based approach: https://en.wikipedia.org/wiki/Outlier#Tukey's_fences

**Comment by tompollard** [comment]
Pull request: https://github.com/tompollard/tableone/pull/44 adds Tukey outlier test to the `cont_describe` table:

![screen shot 2018-03-20 at 09 33 11](https://user-images.githubusercontent.com/822601/37659325-0d4352e4-2c26-11e8-8510-5a9254b10dbe.png)

Also raises warnings if outliers are detected:

![screen shot 2018-03-20 at 09 33 58](https://user-images.githubusercontent.com/822601/37659334-12f50eda-2c26-11e8-8f1a-3438c397f7a3.png)
