### ISSUE TITLE
test that input dataset is not modified

### ISSUE THREAD

**Issue by tompollard** [tompollard/tableone#40]
add test (if it doesn't exist already) for checking that the input dataset isn't modified.

**Comment by alistairewj** [comment]
there is a test here: https://github.com/tompollard/tableone/commit/b1d9c5136688e945c3131a04de0af25505d25a2b

only really tests that the coercion of values to numeric does *not* modify the original dataset

**Comment by tompollard** [comment]
Several more changes added in https://github.com/tompollard/tableone/pull/42/files
