### ISSUE TITLE
Optional Total/Overall column when groupby is used

### ISSUE THREAD

**Issue by tompollard** [tompollard/tableone#50]
Consider adding an option to display an overall/total column when groupby is used (suggested by @theonesp). Miguel, you showed me an example of a paper that did this nicely. Please could you post a screenshot of the table here?

**Comment by theonesp** [comment]
Sure!, please find it below



Miguel

------------------------------

  [image: MIT][image: imes]

*Miguel Ángel Armengol de la Hoz **✉* <maarmeng@mit.edu> / Research
Scientist
*MIT - Institute for Medical Engineering and Science *
*Laboratory for Computational Physiology*
MIT, E25-235- 53 Carleton St.
Cambridge, MA 02139

[image: LinkedIn logo]
<https://www.linkedin.com/in/miguelangelarmengol/?locale=en_US>

**Comment by tompollard** [comment]
![table_1](https://user-images.githubusercontent.com/822601/38275775-fb979744-3760-11e8-8c2c-54ff4e2c7410.png)

**Comment by theonesp** [comment]
Reference:
Subramaniam, B., Lerner, A., Novack, V., Khabbaz, K., Paryente-Wiesmann, M., Hess, P., & Talmor, D. (2014). Increased glycemic variability in patients with elevated preoperative HbA1C predicts adverse outcomes following coronary artery bypass grafting surgery. Anesthesia & Analgesia, 118(2), 277-287.

**Comment by tompollard** [comment]
@theonesp, sorry it took a bit of time to get to this! Version 0.7.1 now includes the overall column by default:

```py
path = "https://raw.githubusercontent.com/tompollard/tableone/master/data/pn2012_demo.csv"

df = pd.read_csv(path)

cols = ["Age", "SysABP", "Height", "Weight", "ICU", "MechVent", "LOS", "death"]
categorical=["ICU", "MechVent", "death"]
strata = "MechVent"

t = TableOne(df, categorical=categorical, label_suffix=True, groupby=strata, 
    pval=True, smd=True)
t
```

![Screen Shot 2020-05-02 at 16 16 40](https://user-images.githubusercontent.com/822601/80891163-522bc180-8c90-11ea-9994-c68daba7ba64.png)
