### ISSUE TITLE
option to append summary type ("mean (SD); median (IQR)") etc to row label

### ISSUE THREAD

**Issue by tompollard** [tompollard/tableone#68]
Add an argument to allow the summary type (e.g. "mean (SD)") to be appended to the row label (e.g. "Age, mean (SD)")

**Comment by jraffa** [comment]
For the median (IQR), please use median(Q1-Q3), if not already done so.

**Comment by tompollard** [comment]
Sure, intentionally with no space between "median" and "(Q1-Q3)"?

**Comment by jraffa** [comment]
nah, that's a typo.  :D
