### ISSUE TITLE
TableOne decimal argument

### ISSUE THREAD

**Issue by PeterStrom** [tompollard/tableone#74]
Hi.

Would be very useful if TableOne had an argument for the number of decimals in the in the percentages e.g. n (%) = 5 (0.23), but with `dec=1` would be 5 (0.2).

**Comment by tompollard** [comment]
@PeterStrom the latest release (v0.5.17) includes a `decimals` argument that allows you to set the number of decimal places reported for continuous and categorical variables.

```
    decimals : int or dict, optional
        Number of decimal places to display. An integer applies the rule to all
        variables (default: 1). A dictionary (e.g. `decimals = {'age': 0)`) applies 
        the rule per variable, defaulting to 1 place for unspecified variables.
        For continuous variables, applies to all summary statistics (e.g. mean and
        standard deviation). For categorical variables, applies to percentage only.
```

I hope this addresses the issue! Version 0.5.17 should be pip installable now, and it will be released on conda forge (https://anaconda.org/conda-forge/tableone) in the next day or two. The notebook includes an example of usage: https://github.com/tompollard/tableone/blob/master/tableone.ipynb

**Comment by PeterStrom** [comment]
Works! Big thanks!
