### ISSUE TITLE
Standard mean difference calculation

### ISSUE THREAD

**Issue by prbndr** [tompollard/tableone#78]
Hi - would it be possible to calculate standard mean differences for a given statistical test, e.g. chi square? In the R version of the package, this is possible by setting smd=TRUE, as a flag when running TableOne. This would be great to have in this package, too!

**Comment by jraffa** [comment]
Hi @prbndr what use case would you like this for?  

I primarily see it used in propensity score analysis, and we haven't really implemented the weighting part of R's `tableone` yet.

**Comment by prbndr** [comment]
Hi - I would like to use this as a balance measure for individual
covariates as opposed to using it after propensity score analysis.
Specifically, I would like to apply this to pooled clinical trial data.

Hope this helps,
Pradeep Bandaru

**Comment by raheems** [comment]
I second the idea of adding smd.

**Comment by tompollard** [comment]
@prbndr @raheems we'll try to get onto this soon

**Comment by raheems** [comment]
No rush but just checking if this feature has been added or in progress :)

**Comment by tompollard** [comment]
I'll try to take a look today.

**Comment by tompollard** [comment]
Computing the SMD for categorical was more work than I'd expected! The current version on the master branch includes a new `smd` argument. Before we push to pypi, it would be great to have your feedback. Some demo cases (with comparisons to R) are described at: https://github.com/tompollard/tableone/pull/97

**Comment by tompollard** [comment]
This is now on pypi (version 0.7.0). Please test! 

It will be on Conda shortly.

**Comment by tompollard** [comment]
Quickest way to play around it is probably to use the notebook at:
https://colab.research.google.com/github/tompollard/tableone/blob/master/tableone.ipynb

Just add `smd = True` to the arguments.
